server:
  port: 28180

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-}] [%thread] %-5level %logger{36} - %msg%n"

spring:
  config:
    name: AIA-CONSOLE
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/analysis_platform?rewriteBatchedStatements=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

common:
  api-logging:
    enabled: false

console:
  app-base-url: http://localhost:28080
  security:
    username: admin
    password: admin
